version: '3.9'

services:
  mongo:
    image: mongo:5.0.0
    container_name: klinics-mongo
    networks:
      - klinics-network
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

#  prod:
#    container_name: klinics-prod
#    build: .
#    volumes:
#      - .:/app
#      - /app/node_modules
#    ports:
#      - 80:3000
#    networks:
#      - klinics-network
#    command:
#      - pnpm run build
#      - pnpm run start:prod
#    env_file:
#      - .env.production
#    restart: unless-stopped
#    depends_on:
#      - mongodb

  dev:
    container_name: klinics-dev
    build:
      dockerfile: ./DockerfileDev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - klinics-network
    env_file:
      - .env.development
    restart: unless-stopped
    depends_on:
      - mongo

networks:
  klinics-network:
volumes:
  mongodb_data_container:
